# Generated by Django 6.1 on 2026-08-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('audio', models.FileField(blank=True, null=True, upload_to='blog/audio/', verbose_name='Аудио')),
                ('video', models.FileField(blank=True, null=True, upload_to='blog/video/', verbose_name='Видео')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео (YouTube)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created'],
            },
        ),
    ]
