# Generated by Django 6.1 on 2026-08-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('title', models.CharField(max_length=100, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение')),
                ('technologies', models.CharField(blank=True, max_length=300, verbose_name='Технологии')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('level', models.PositiveSmallIntegerField(default=5, verbose_name='Уровень (1-10)')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
