# Generated by Django 6.1 on 2026-09-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('higher', 'Высшее'), ('course', 'Курсы')], default='higher', max_length=20, verbose_name='Тип')),
                ('year', models.CharField(max_length=20, verbose_name='Год')),
                ('place', models.CharField(max_length=200, verbose_name='Место')),
                ('program', models.CharField(blank=True, max_length=300, verbose_name='Специальность/программа')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Язык')),
                ('level', models.CharField(blank=True, max_length=100, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
                ('label', models.CharField(max_length=150, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_photo',
            field=models.BooleanField(default=True, verbose_name='Показывать фото'),
        ),
    ]
