# Generated by Django 6.1 on 2026-09-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education_language_metric_profile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.AddField(
            model_name='experience',
            name='duties',
            field=models.TextField(blank=True, verbose_name='Функционал (по строке на пункт)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='results',
            field=models.TextField(blank=True, verbose_name='Ключевые результаты (по строке на пункт)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
